### ISSUE TITLE
Viewing a file in a public directory fails

### ISSUE THREAD

**Issue by armaccloud** [owncloudarchive/documents#413]
Hi,
When someone has opened a shared folder from a public on my owncloud, they cannot preview / download any ODT files by clicking on them (not using the download button). From within the normal Owncloud interface the preview works fine. I don't know whether from a public link the preview or download behaviour should occur when clicking on it.
I am using owncloud 7.03 on Ubuntu Server 14.04 LTS

![owncloud open odt](https://cloud.githubusercontent.com/assets/9272078/5234724/15e3e7f4-77db-11e4-93ca-eda932385637.jpg)

Thanks.

**Comment by jcharaoui** [comment]
Is there a temporary workaround to avoid this error? It's quite confusing to users as most will try to click the filename to download or view the file.
